name: Test end to end

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: test
        run: echo ${{ secrets.TEST }}
      - name: Create .env file
        run: |
          touch .env
          echo NOTION_TOKEN =${{ secrets.NOTION_TOKEN }} >> .env
          echo NOTION_DATABASE_ID =${{ secrets.NOTION_DATABASE_ID }} >> .env
          echo ENGLISH_NOTION_DATABASE_ID =${{ secrets.ENGLISH_NOTION_DATABASE_ID }} >> .env
          echo NOTION_MORE_DATABASE =${{ secrets.NOTION_MORE_DATABASE }} >> .env
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          build: npm run build
          start: npm start
          wait-on: http://localhost:3000